let songTitles = [
    "\"Absolute Soul\" by Konomi Suzuki", 
    "\"Acchi de Kocchi de\" by Acchi⇔Kocchi", 
    "\"Skyreach\" by Sora Amamiya", 
    "\"LIAR MASK\" by Rika Mayama", 
    "\"Aoi Shiori\" by Galileo Galilei", 
    "\"Circle Game\" by Galileo Galilei", 
    "\"Kyoumu Densen\" by ALI PROJECT", 
    "\"Jiriki Hongan Revolution\" by 3-nen E-gumi Utatan", 
    "\"CORE PRIDE\" by UVERworld", 
    "\"IN MY WORLD\" by ROOKiEZ is PUNK'D", 
    "\"Itteki no Eikyou\" by UVERworld", 
    "\"Gun's & Roses\" by Paradise Lunch", 
    "\"black bullet\" by fripSide", 
    "\"Red Fraction\" by MELL",
    "\"Re:Re:\" by Asian Kung-Fu Generation",
    "\"The Day\" by Porno Graffitti",
    "\"No pain, No game\" by Nano",
    "\"Exist\" by Nano",
    "\"Bravely You\" by Lia",
    "\"Sparkling Daydream\" by ZAQ",
    "\"For You\" by ZAQ",
    "\"VOICE\" by ZAQ",
    "\"COLORS\" by FLOW",
    "\"Kaidoku Funou\" by Jinn",
    "\"Hitomi no Tsubasa\" by Access",
    "\"02~O-Two~\" by Orange Range",
    "\"WORLD END\" by FLOW",
    "\"Tank!\" by The Seatbelts",
    "\"Checkmate!?\" by MICHI",
    "\"Howling\" by Abingdon Boys School",
    "\"Kakusei Heroism ~The Hero without a Name~\" by An Cafe ",
    "\"Flyers\" by BRADIO",
    "\"Hey World\" by Yuka Iguchi",
    "\"Lilium\" by Kumiko Noma"];