let songTitles = [
    "\"Absolute Soul\" by Konomi Suzuki", 
    "\"Acchi de Kocchi de\" by Acchi⇔Kocchi", 
    "\"Skyreach\" by Sora Amamiya", 
    "\"LIAR MASK\" by Rika Mayama", 
    "\"Aoi Shiori\" by Galileo Galilei", 
    "\"Circle Game\" by Galileo Galilei", 
    "\"Kyoumu Densen\" by ALI PROJECT", 
    "\"Jiriki Hongan Revolution\" by 3-nen E-gumi Utatan", 
    "\"CORE PRIDE\" by UVERworld", 
    "\"IN MY WORLD\" by ROOKiEZ is PUNK'D", 
    "\"Itteki no Eikyou\" by UVERworld", 
    "\"Gun's & Roses\" by Paradise Lunch", 
    "\"black bullet\" by fripSide", 
    "\"Red Fraction\" by MELL",
    "\"Re:Re:\" by Asian Kung-Fu Generation",
    "\"The Day\" by Porno Graffitti",
    "\"No pain, No game\" by Nano",
    "\"Exist\" by Nano",
    "\"Bravely You\" by Lia",
    "\"Sparkling Daydream\" by ZAQ",
    "\"For You\" by ZAQ",
    "\"VOICE\" by ZAQ",
    "\"COLORS\" by FLOW",
    "\"Kaidoku Funou\" by Jinn",
    "\"Hitomi no Tsubasa\" by Access",
    "\"02~O-Two~\" by Orange Range",
    "\"WORLD END\" by FLOW",
    "\"Tank!\" by The Seatbelts",
    "\"Checkmate!?\" by MICHI",
    "\"Howling\" by Abingdon Boys School",
    "\"Kakusei Heroism ~The Hero without a Name~\" by An Cafe ",
    "\"Flyers\" by BRADIO",
    "\"Hey World\" by Yuka Iguchi",
    "\"Lilium\" by Kumiko Noma",
    "\"MASAYUME CHASING\" by BoA",
    "\"STRIKE BACK\" by BACK-ON",
    "\"Mysterious Magic\" by Do As Infinity",
    "\"BREAK OUT\" by V6",
    "\"Snow fairy\" by FUNKIST",
    "\"S.O.W. Sense of Wonder\" by Idoling!!!",
    "\"ft.\" by FUNKIST",
    "\"R.P.G. ~Rockin' Playing Game\" by SuG",
    "\"Egao No Mahou\" by Magic Party",
    "\"Fiesta\" by +Plus",
    "\"Evidence\" by Daisy X Daisy",
    "\"The Rock City Boy\" by JAMIL",
    "\"Towa no Kizuna\" by Daisy x Daisy feat. Another Infinity",
    "\"I Wish\" by Milky Bunny",
    "\"The Starting Sky\" by +Plus",
    "\"Tenohira\" by HERO",
    "\"Break through\" by GOING UNDER GROUND",
    "\"Fairy Tail ~Yakusoku no Hi~\" by Chihiro Yonekura",
    "\"again\" by YUI",
    "\"Hologram\" by NICO Touches the Walls",
    "\"Golden Time Lover\" by Sukima Switch",
    "\"Period\" by Chemistry",
    "\"Rain\" by SID",
    "\"Melissa\" by Porno Graffitti",
    "\"READY STEADY GO\" by L'Arc~en~Ciel",
    "\"UNDO\" by Cool Joke",
    "\"Rewrite\" by Asian Kung-fu Generation",
    "\"Friend Shitai\" by Gakuen Seikatsubu",
    "\"Brand-new World\" by Shiena Nishizawa ",
    "\"GATE: Sore wa Akatsuki no you ni\" by Kishida Kyoudan & The Akeboshi Rockets",
    "\"GATE II: Sekai wo Koete\" by Kishida Kyoudan & The Akeboshi Rockets",
    "\"Pray\" by Tommy heavenly6",
    "\"Tooi Nioi\" by YO-KING",
    "\"Giniro no Sora\" by redballoon",
    "\"Kasanaru Kage\" by Hearts Grow",
    "\"DONTEN\" by DOES",
    "\"Anata MAGIC\" by monobright",
    "\"Stairway Generation\" by Base Ball Bear",
    "\"Light Infection\" by Prague",
    "\"BRYNHILDR IN THE DARKNESS -Ver. EJECTED-\" by Nao Tokisawa",
    "\"Virtue and Vice\" by Fear, and loathing in Las Vegas",
    "\"Euterpe\" by EGOIST; produced by supercell; performed by Chelly",
    "\"My Dearest\" by supercell; performed by Koeda",
    "\"Knew day\" by (K)NoW_NAME",
    "\"ZERO!!\" by Minami Kuribayashi",
    "\"Ohayou\" by Keno",
    "\"Taiyou wa Yoru mo Kagayaku\" by Wino ",
    "\"departure!\" by Ono Masatoshi ",
    "\"Nirvana\" by MUCC",
    "\"Niji no Kakera\" by Natsumi Kon",
    "\"JoJo - Sono Chi no Kioku: end of THE WORLD\" by JO☆STARS～TOMMY, Coda, JIN～",
    "\"STAND PROUD\" by Jin Hashimoto",
    "\"JoJo ~Sono Chi no Sadame~\" by Hiroaki TOMMY Tominaga",
    "\"BLOODY STREAM\" by Coda",
    "\"Kawaru Mirai\" by Choucho",
    "\"Hello, world!\" by BUMP OF CHICKEN",
    "\"Sirius\" by Eir Aoi",
    "\"ambiguous\" by GARNiDELiA",
    "\"Yume Tourou\" by RADWIMPS",
    "\"LAY YOUR HANDS ON ME\" by BOOM BOOM SATELLITES",
    "\"Aozora no Rhapsody\" by fhána",
    "\"My Generation\" by The Who",
    "\"fantastic dreamer\" by Machico",
    "\"TOMORROW\" by Machico",
    "\"V.I.P\" by SID",
    "\"ANNIVERSARY\" by SID",
    "\"Hikari\" by ViViD",
    "\"Rising Hope\" by LiSA",
    "\"grilletto\" by GARNiDELiA",
    "\"daze\" by Jin ft. MARiA from GARNiDELiA",
    "\"Kuusou Mesorogiwi\" by Yousei Teikoku",
    "\"Dead END\" by Faylan",
    "\"Kyouki Chinden\" by Yousei Teikoku",
    "\"Black † White\" by Iori Nomizu",
    "\"Saikousoku Fall in Love\" by Miia",
    "\"Naked Dive\" by SCREEN mode",
    "\"Seven Deadly Sins\" by MAN WITH A MISSION",
    "\"Zankoku na Tenshi no Thesis (A Cruel Angel's Thesis)\" by Yoko Takahashi",
    "\"1st Love Story\" by Luce Twinkle Wink☆",
    "\"CLICK\" by ClariS",
    "\"STEP\" by ClariS",
    "\"Rally Go Round\" by LiSA",
    "\"Magical☆Styling\" by Magical Pâtissière Kosaki-chan",
    "\"This game\" by Konomi Suzuki",
    "\"Goya no Machiawase\" by Hello Sleepwalkers",
    "\"Kyouran Hey Kids!!\" by THE ORAL CIGARETTES"];