let titles = [
    "Absolute Duo", 
    "Acchi Kocchi", 
    "Akame Ga Kill", 
    "Akame Ga Kill", 
    "Anohana", 
    "Anohana", 
    "Another", 
    "Assassination Classroom", 
    "Blue Exorcist", 
    "Blue Exorcist", 
    "Blue Exorcist: Kyoto Saga", 
    "Baccano!", 
    "Black Bullet", 
    "Black Lagoon",
    "ERASED",
    "My Hero Academia",
    "Btooom!",
    "Btooom!",
    "Charlotte",
    "Love, Chunibyo & Other Delusions!",
    "Love, Chunibyo & Other Delusions!",
    "Love, Chunibyo & Other Delusions!: Heart Throb",
    "Code Geass: Lelouch of the Rebellion",
    "Code Geass: Lelouch of the Rebellion",
    "Code Geass: Lelouch of the Rebellion",
    "Code Geass: Lelouch of the Rebellion R2",
    "Code Geass: Lelouch of the Rebellion R2",
    "Cowboy Bebop",
    "Dagashi Kashi",
    "Darker Than Black",
    "Darker Than Black",
    "Death Parade",
    "Is It Wrong to Try to Pick Up Girls in a Dungeon?",
    "Elfen Lied",
    "Fairy Tail (2014)",
    "Fairy Tail (2014)",
    "Fairy Tail (2014)",
    "Fairy Tail (2014)",
    "Fairy Tail",
    "Fairy Tail",
    "Fairy Tail",
    "Fairy Tail",
    "Fairy Tail",
    "Fairy Tail",
    "Fairy Tail",
    "Fairy Tail",
    "Fairy Tail",
    "Fairy Tail",
    "Fairy Tail",
    "Fairy Tail",
    "Fairy Tail",
    "Fairy Tail",
    "Fullmetal Alchemist：Brotherhood",
    "Fullmetal Alchemist：Brotherhood",
    "Fullmetal Alchemist：Brotherhood",
    "Fullmetal Alchemist：Brotherhood",
    "Fullmetal Alchemist：Brotherhood",
    "Fullmetal Alchemist",
    "Fullmetal Alchemist",
    "Fullmetal Alchemist",
    "Fullmetal Alchemist",
    "School-Live!",
    "The Asterisk War",
    "GATE",
    "GATE",
    "Gintama",
    "Gintama",
    "Gintama",
    "Gintama",
    "Gintama",
    "Gintama",
    "Gintama",
    "Gintama",
    "Brynhildr in the Darkness",
    "Brynhildr in the Darkness",
    "Guilty Crown",
    "Guilty Crown",
    "Grimgar: Ashes and Illusions",
    "The Devil is a Part-Timer!",
    "Hunter x Hunter (1999)",
    "Hunter x Hunter (1999)",
    "Hunter x Hunter (2011)",
    "Inu X Boku Secret Service",
    "One Week Friends",
    "JoJo's Bizarre Adventure: Stardust Crusaders - Battle in Egypt",
    "JoJo's Bizarre Adventure: Stardust Crusaders",
    "JoJo's Bizarre Adventure",
    "JoJo's Bizarre Adventure",
    "Heaven's Memo Pad",
    "Blood Blockade Battlefront",
    "Kill la Kill",
    "Kill la Kill",
    "Your Name.",
    "Kiznaiver",
    "Miss Kobayashi's Dragon Maid",
    "A Silent Voice",
    "KonoSuba: God's Blessing on This Wonderful World!",
    "KonoSuba: God's Blessing on This Wonderful World! 2",
    "Magi: The Labyrinth of Magic",
    "Magi: The Kingdom of Magic",
    "Magi: The Kingdom of Magic",
    "The Irregular at Magic High School",
    "The Irregular at Magic High School",
    "Mekakucity Actors"];