let titles = [
    "Absolute Duo", 
    "Acchi Kocchi", 
    "Akame Ga Kill", 
    "Akame Ga Kill", 
    "Anohana", 
    "Anohana", 
    "Another", 
    "Assassination Classroom", 
    "Blue Exorcist", 
    "Blue Exorcist", 
    "Blue Exorcist: Kyoto Saga", 
    "Baccano!", 
    "Black Bullet", 
    "Black Lagoon",
    "ERASED",
    "My Hero Academia",
    "Btooom!",
    "Btooom!",
    "Charlotte",
    "Love, Chunibyo & Other Delusions!",
    "Love, Chunibyo & Other Delusions!",
    "Love, Chunibyo & Other Delusions!: Heart Throb",
    "Code Geass: Lelouch of the Rebellion",
    "Code Geass: Lelouch of the Rebellion",
    "Code Geass: Lelouch of the Rebellion",
    "Code Geass: Lelouch of the Rebellion R2",
    "Code Geass: Lelouch of the Rebellion R2",
    "Cowboy Bebop",
    "Dagashi Kashi"];